--1.
SELECT 
	EMP_NAME,
	DEPT_CODE,
	SALARY
FROM EMPLOYEE e
WHERE DEPT_CODE = (SELECT DEPT_ID FROM DEPARTMENT WHERE dept_title = '기술지원부');


--2.
SELECT
	EMP_NAME,
	dept_code,
	salary
FROM
	(
	SELECT
		EMP_NAME,
		DEPT_CODE,
		SALARY,
		rownum
	FROM
		EMPLOYEE e
	JOIN DEPARTMENT d ON e.DEPT_CODE = d.DEPT_ID
	WHERE
		d.DEPT_ID = ( SELECT DEPT_ID FROM DEPARTMENT d WHERE d.DEPT_TITLE = '기술지원부')
	ORDER BY
		e.salary DESC
)
WHERE
	rownum = 1;


--3.
---- 1) using join
SELECT
	e1.EMP_ID AS "사번",
	e1.EMP_NAME AS "이름",
	e2.EMP_NAME AS "매니저 이름",
	e1.SALARY AS "월급"
FROM EMPLOYEE e1 JOIN EMPLOYEE e2
ON e1.MANAGER_ID = e2.EMP_ID 
CROSS join (SELECT AVG(SALARY) AS "average" FROM EMPLOYEE)
WHERE e1.SALARY > "average"
ORDER BY 1;

----- 2) using correlation
SELECT
	EMP_ID AS "사번",
	EMP_NAME AS "이름",
	(SELECT e2.EMP_NAME FROM EMPLOYEE e2 WHERE e.MANAGER_ID = e2.EMP_ID) AS "매니저 이름",
	SALARY AS "월급"
FROM EMPLOYEE e
WHERE salary > (SELECT AVG(salary) FROM EMPLOYEE)
	AND MANAGER_ID IS NOT NULL
ORDER BY 1;


--4.
SELECT
	EMP_NAME,
	JOB_CODE,
	SALARY,
	SAL_LEVEL 
FROM EMPLOYEE e
WHERE SALARY >= (SELECT AVG(SALARY) FROM EMPLOYEE e2 WHERE JOB_CODE = e.JOB_CODE);


--5.
SELECT
	nvl((SELECT dept_title FROM DEPARTMENT WHERE DEPT_ID = e.DEPT_CODE), '인턴'),
	trunc(AVG(e.SALARY))
FROM EMPLOYEE e
GROUP BY e.DEPT_CODE
HAVING AVG(e.SALARY) > 3000000 ;


--6.
SELECT
	EMP_NAME,
	(SELECT JOB_NAME FROM JOB j WHERE JOB_CODE = e.JOB_CODE) AS "직급",
	dept_code,
	(SELECT dept_title FROM DEPARTMENT WHERE DEPT_ID = e.DEPT_CODE) AS "부서",
	salary * (1 + nvl(bonus,0)) * 12

FROM EMPLOYEE e 
WHERE
salary * (1 + nvl(BONUS,0)) < (SELECT AVG(SALARY * (1 + nvl(BONUS,0))) FROM EMPLOYEE e2 WHERE JOB_CODE = e.JOB_CODE)
AND substr(EMP_NO, 8, 1) IN (2, 4);


--7.
SELECT DISTINCT
	BOOK_TITLE 
FROM TBL_BOOKS tb
WHERE 1 < (SELECT count(*) FROM TBL_BOOKS tb2 WHERE BOOK_TITLE = tb.BOOK_TITLE);