--1.
WITH EMP_VIEW
AS
(SELECT EMP_ID, EMP_NAME, EXTRACT(YEAR FROM HIRE_DATE) as "HIRE_YEAR" FROM EMPLOYEE)
SELECT
	EMP_ID AS "사번",
	EMP_NAME AS "사원명",
	HIRE_YEAR AS "입사년도"
FROM EMP_VIEW
WHERE HIRE_YEAR BETWEEN 1990 and 1999;

--2.
WITH EMP_VIEW
AS
(SELECT EMP_ID, EMP_NAME, DEPT_CODE, DECODE(SUBSTR(EMP_NO, 8, 1), '2', 19, '4', 20) || SUBSTR(EMP_NO, 1, 2) AS "BIRTH_YEAR", SUBSTR(EMP_NO, 8, 1) AS "GENDER"  FROM EMPLOYEE )
SELECT
	EMP_ID AS "사번",
	EMP_NAME AS "사원명",
	d.DEPT_TITLE AS "부서명",
	'여' AS "성별",
	EXTRACT(YEAR FROM SYSDATE) - BIRTH_YEAR AS "나이"
FROM EMP_VIEW e LEFT JOIN DEPARTMENT d 
ON e.DEPT_CODE = d.DEPT_ID
WHERE (GENDER in (2, 4)) AND (EXTRACT(YEAR FROM SYSDATE) - BIRTH_YEAR BETWEEN 30 and 49)
ORDER BY 1;